server:
  port: 9000

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: postModule
          uri: lb://INST-POST-SERVICE
          predicates:
            - Path=/post/**
        - id: photoModule
          uri: lb://INST-PHOTO-SERVICE
          predicates:
            - Path=/photo/**
        - id: commentsModule
          uri: lb://INST-COMMENT-SERVICE
          predicates:
            - Path=/comment/**
        - id: scoresModule
          uri: lb://INST-SCORES-SERVICE
          predicates:
           - Path=/score/**
        - id: eureka
          uri: lb://EUREKA-SERVER
          predicates:
            - Path=/eureka/**